### ISSUE TITLE
For me, no error, but both tables [SKMemories] and [SKMemoryCollections] are empty

### ISSUE THREAD

**Issue by ajmal-yazdani** [marcominerva/OpenAIEmbeddingSample#4]
Hello,

Thanks for your share. I tried to run the program as it is. I am not seeing any error while trying to uplaod a pdf file, but both tables [SKMemories] and [SKMemoryCollections] are empty and no memories generated.

Any suggestion please?

info: Microsoft.KernelMemory.Handlers.TextExtractionHandler[0]
      Handler 'extract' ready
info: Microsoft.KernelMemory.Handlers.TextPartitioningHandler[0]
      Handler 'partition' ready
info: Microsoft.KernelMemory.Handlers.SummarizationHandler[0]
      Handler 'summarize' ready
info: Microsoft.KernelMemory.Handlers.GenerateEmbeddingsHandler[0]
      Handler 'gen_embeddings' ready, 1 embedding generators
info: Microsoft.KernelMemory.Handlers.SaveRecordsHandler[0]
      Handler save_records ready, 1 vector storages
info: Microsoft.KernelMemory.Handlers.DeleteDocumentHandler[0]
      Handler 'private_delete_document' ready
info: Microsoft.KernelMemory.Handlers.DeleteIndexHandler[0]
      Handler 'private_delete_index' ready
info: Microsoft.KernelMemory.Handlers.DeleteGeneratedFilesHandler[0]
      Handler 'delete_generated_files' ready
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      Queueing upload of 1 files for further processing [request 2a4e1d6d2dd842f29957ccda4e9eeeff202401230325092344298]
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      File uploaded: LIC.pdf, 189007 bytes
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      Handler 'extract' processed pipeline 'default/2a4e1d6d2dd842f29957ccda4e9eeeff202401230325092344298' successfully
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      Handler 'partition' processed pipeline 'default/2a4e1d6d2dd842f29957ccda4e9eeeff202401230325092344298' successfully
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      Handler 'gen_embeddings' processed pipeline 'default/2a4e1d6d2dd842f29957ccda4e9eeeff202401230325092344298' successfully
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      Handler 'save_records' processed pipeline 'default/2a4e1d6d2dd842f29957ccda4e9eeeff202401230325092344298' successfully
info: Microsoft.KernelMemory.Pipeline.BaseOrchestrator[0]
      Pipeline 'default/2a4e1d6d2dd842f29957ccda4e9eeeff202401230325092344298' complete

> Question: how much payment I made
info: Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAIChatCompletionService[0]
      Prompt tokens: 93. Completion tokens: 11. Total tokens: 104.
warn: Microsoft.KernelMemory.Search.SearchClient[0]
      No memories available
I'm sorry, I haven't found any relevant information about that can be used to answer your question

> Question:

**Comment by marcominerva** [comment]
Are you using the latest version of the project? I have retried just now, and **SKMemories** and **SKMemoryCollections** are correctly populated.

According to the log, it seems that your **LIC.pdf** file has been processed correctly. You can try uncommenting [this line](https://github.com/marcominerva/OpenAIEmbeddingSample/blob/master/EmbeddingSample/Program.cs#L40) in **Program.cs** (after setting the corresponding constant), so that the partition are persisted on file system, in the path you have set. In this way, you can verify if the partitions are correctly retrieved:

```csharp
//.WithSimpleFileStorage(AppConstants.Memory.ContentStoragePath)  // Uncomment to use persistent content storage. 
```

If this doesn't help you with the issue, it may be a problem with the SQL Server connector. I suggest you to fill an issue on the https://github.com/kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer repository, so that the author of the SQL Server Memory Connector can assist you further.

**Comment by marcominerva** [comment]
I'm closing this issue since there hasn't been activities since Jan 23. If you still have the issue, feel free to reopen it.
